### ISSUE TITLE
Better error message for component missing schema

### ISSUE THREAD

**Issue by cruzanmo** [clay/amphora#403]
It would be helpful to log which component is causing the schema error.

Two cases when a schema would throw an error:
- when a component's schema is missing or invalid
- when a component is referenced in the data and the component does not exist in the file system

Current error message example:
```
error: node_modules/amphora/lib/responses:: TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.getSchemaPath (/Users/mcroney/_dev/sites/node_modules/amphora/lib/schema.js:23:24)
    at /Users/mcroney/_dev/sites/node_modules/amphora/lib/html-composer.js:102:24
    at arrayMap (/Users/mcroney/_dev/sites/node_modules/lodash/lodash.js:660:23)
    at Function.map (/Users/mcroney/_dev/sites/node_modules/lodash/lodash.js:9571:14)
    at /Users/mcroney/_dev/sites/node_modules/amphora/lib/html-composer.js:99:41
From previous event:
    at renderByConfiguration (/Users/mcroney/_dev/sites/node_modules/amphora/lib/html-composer.js:142:6)
    at /Users/mcroney/_dev/sites/node_modules/amphora/lib/html-composer.js:230:18
From previous event:
    at /Users/mcroney/_dev/sites/node_modules/amphora/lib/html-composer.js:221:10
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Function.renderPage (/Users/mcroney/_dev/sites/node_modules/amphora/lib/html-composer.js:214:6)
    at /Users/mcroney/_dev/sites/node_modules/amphora/lib/routes/pages.js:91:27
From previous event:
    at Object.expectHTML (/Users/mcroney/_dev/sites/node_modules/amphora/lib/responses.js:422:15)
    at Object.render (/Users/mcroney/_dev/sites/node_modules/amphora/lib/routes/pages.js:90:15)
    at Object.wrapper [as render] (/Users/mcroney/_dev/sites/node_modules/lodash/lodash.js:4968:19)
    at Object.extension (/Users/mcroney/_dev/sites/node_modules/amphora/lib/routes/pages.js:76:14)
    at wrapper (/Users/mcroney/_dev/sites/node_modules/lodash/lodash.js:4968:19)
    at Layer.handle [as handle_request] (/Users/mcroney/_dev/sites/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/mcroney/_dev/sites/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/mcroney/_dev/sites/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/mcroney/_dev/sites/node_modules/express/lib/router/layer.js:95:5)
    at /Users/mcroney/_dev/sites/node_modules/express/lib/router/index.js:281:22
    at param (/Users/mcroney/_dev/sites/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/mcroney/_dev/sites/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/mcroney/_dev/sites/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/mcroney/_dev/sites/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/mcroney/_dev/sites/node_modules/express/lib/router/index.js:275:10)
    at next (/Users/mcroney/_dev/sites/node_modules/express/lib/router/route.js:127:14)
    at /Users/mcroney/_dev/sites/node_modules/amphora/lib/responses.js:314:7
    at Layer.handle [as handle_request] (/Users/mcroney/_dev/sites/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/mcroney/_dev/sites/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/mcroney/_dev/sites/node_modules/express/lib/router/route.js:112:3)
Warning: failed to get data from localhost.dev.nymag.biz/scienceofus/components/most-popular/instances/scienceofus, using empty data
```

**Comment by jonwinton** [comment]
There is a specific `Schema not found!` message now
