### ISSUE TITLE
Error for no site config.yaml

### ISSUE THREAD

**Issue by jasondecastro** [clay/amphora#406]
https://github.com/nymag/amphora/blob/master/lib/services/sites.js#L62-L67

When no `config.yml` is present in a site's directory we should throw a more descriptive error.

```error: :: TypeError: Cannot set property 'slug' of undefined
    at /Users/jdecastro/Desktop/Development/sites/node_modules/amphora/lib/services/sites.js:64:21
    at Array.forEach (native)
    at getSites (/Users/jdecastro/Desktop/Development/sites/node_modules/amphora/lib/services/sites.js:51:41)
    at memoized (/Users/jdecastro/Desktop/Development/sites/node_modules/lodash/lodash.js:10566:27)
    at Object.controlFn [as sites] (/Users/jdecastro/Desktop/Development/sites/node_modules/amphora/lib/control.js:86:28)
    at loadFromConfig (/Users/jdecastro/Desktop/Development/sites/node_modules/amphora/lib/routes.js:333:32)
    at module.exports (/Users/jdecastro/Desktop/Development/sites/node_modules/amphora/lib/setup.js:40:12)
    at /Users/jdecastro/Desktop/Development/sites/app.js:71:12
From previous event:
    at Object.<anonymous> (/Users/jdecastro/Desktop/Development/sites/app.js:53:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3

```

**Comment by jonwinton** [comment]
<img width="682" alt="screen shot 2018-05-03 at 3 59 15 pm" src="https://user-images.githubusercontent.com/4906712/39599854-ff97473a-4eea-11e8-9f2d-ca12982cf494.png">
